name 'formatron_rabbitmq'
version '0.1.1'
description 'Formatron RabbitMQ cookbook'
maintainer 'Peter Halliday'
maintainer_email 'pghalliday@gmail.com'
source_url 'https://github.com/formatron/rabbitmq-cookbook'
issues_url 'https://github.com/formatron/rabbitmq-cookbook/issues'
supports 'ubuntu'
depends 'apt'
